/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentLibraryInput = IDL.Record({
  'serviceName' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Opt(IDL.Text),
});
export const ExpenseInput = IDL.Record({
  'date' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const RenewalInput = IDL.Record({
  'documentBlob' : IDL.Opt(ExternalBlob),
  'serviceName' : IDL.Text,
  'govtFees' : IDL.Float64,
  'serviceCharge' : IDL.Float64,
  'nextExpiryDate' : IDL.Int,
  'advancePaid' : IDL.Float64,
  'customerId' : IDL.Text,
  'renewalDate' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'in_process' : IDL.Null,
});
export const CustomerInput = IDL.Record({
  'serviceType' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'govtFees' : IDL.Float64,
  'applicationNo' : IDL.Opt(IDL.Text),
  'expiryDate' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'deliveryDate' : IDL.Opt(IDL.Int),
  'totalCharged' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'advancePaid' : IDL.Float64,
  'phone' : IDL.Text,
  'applicationDate' : IDL.Int,
  'currentStatus' : Status,
  'documentBlobIds' : IDL.Vec(ExternalBlob),
  'customServiceName' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CustomerRecord = IDL.Record({
  'serviceType' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'isDeleted' : IDL.Bool,
  'tokenId' : IDL.Text,
  'govtFees' : IDL.Float64,
  'applicationNo' : IDL.Opt(IDL.Text),
  'expiryDate' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'deliveryDate' : IDL.Opt(IDL.Int),
  'totalCharged' : IDL.Float64,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Opt(IDL.Text),
  'advancePaid' : IDL.Float64,
  'balanceDue' : IDL.Float64,
  'phone' : IDL.Text,
  'applicationDate' : IDL.Int,
  'currentStatus' : Status,
  'deletedAt' : IDL.Opt(IDL.Int),
  'netProfit' : IDL.Float64,
  'documentBlobIds' : IDL.Vec(ExternalBlob),
  'customServiceName' : IDL.Opt(IDL.Text),
});
export const RenewalRecord = IDL.Record({
  'id' : IDL.Text,
  'documentBlob' : IDL.Opt(ExternalBlob),
  'serviceName' : IDL.Text,
  'govtFees' : IDL.Float64,
  'serviceCharge' : IDL.Float64,
  'createdAt' : IDL.Int,
  'totalCharged' : IDL.Float64,
  'nextExpiryDate' : IDL.Int,
  'advancePaid' : IDL.Float64,
  'balanceDue' : IDL.Float64,
  'customerId' : IDL.Text,
  'renewalDate' : IDL.Int,
});
export const ExpenseSummary = IDL.Record({
  'today' : IDL.Float64,
  'total' : IDL.Float64,
  'thisMonth' : IDL.Float64,
});
export const ProfitSummary = IDL.Record({
  'today' : IDL.Float64,
  'thisMonth' : IDL.Float64,
  'totalNetProfit' : IDL.Float64,
});
export const CustomServiceEntry = IDL.Record({
  'name' : IDL.Text,
  'addedAt' : IDL.Int,
  'category' : IDL.Text,
});
export const DocumentLibraryItem = IDL.Record({
  'id' : IDL.Text,
  'serviceName' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Opt(IDL.Text),
  'uploadedAt' : IDL.Int,
});
export const ExpenseRecord = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomService' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'addDocumentLibraryItem' : IDL.Func([DocumentLibraryInput], [IDL.Text], []),
  'addExpense' : IDL.Func([ExpenseInput], [IDL.Text], []),
  'addRenewalRecord' : IDL.Func([RenewalInput], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'createCustomer' : IDL.Func([CustomerInput], [IDL.Text], []),
  'deleteDocumentLibraryItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteExpense' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [CustomerRecord], ['query']),
  'getCustomerRenewalHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RenewalRecord)],
      ['query'],
    ),
  'getExpenseSummary' : IDL.Func([], [ExpenseSummary], ['query']),
  'getProfitSummary' : IDL.Func([], [ProfitSummary], ['query']),
  'getUpcomingRenewals' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CustomerRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomServices' : IDL.Func([], [IDL.Vec(CustomServiceEntry)], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(CustomerRecord)], ['query']),
  'listDeletedCustomers' : IDL.Func([], [IDL.Vec(CustomerRecord)], ['query']),
  'listDocumentLibraryItems' : IDL.Func(
      [],
      [IDL.Vec(DocumentLibraryItem)],
      ['query'],
    ),
  'listExpenses' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
  'restoreCustomer' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'softDeleteCustomer' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateCustomer' : IDL.Func([IDL.Text, CustomerInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentLibraryInput = IDL.Record({
    'serviceName' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Opt(IDL.Text),
  });
  const ExpenseInput = IDL.Record({
    'date' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const RenewalInput = IDL.Record({
    'documentBlob' : IDL.Opt(ExternalBlob),
    'serviceName' : IDL.Text,
    'govtFees' : IDL.Float64,
    'serviceCharge' : IDL.Float64,
    'nextExpiryDate' : IDL.Int,
    'advancePaid' : IDL.Float64,
    'customerId' : IDL.Text,
    'renewalDate' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'in_process' : IDL.Null,
  });
  const CustomerInput = IDL.Record({
    'serviceType' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'govtFees' : IDL.Float64,
    'applicationNo' : IDL.Opt(IDL.Text),
    'expiryDate' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'deliveryDate' : IDL.Opt(IDL.Int),
    'totalCharged' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'advancePaid' : IDL.Float64,
    'phone' : IDL.Text,
    'applicationDate' : IDL.Int,
    'currentStatus' : Status,
    'documentBlobIds' : IDL.Vec(ExternalBlob),
    'customServiceName' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CustomerRecord = IDL.Record({
    'serviceType' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'isDeleted' : IDL.Bool,
    'tokenId' : IDL.Text,
    'govtFees' : IDL.Float64,
    'applicationNo' : IDL.Opt(IDL.Text),
    'expiryDate' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'deliveryDate' : IDL.Opt(IDL.Int),
    'totalCharged' : IDL.Float64,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Opt(IDL.Text),
    'advancePaid' : IDL.Float64,
    'balanceDue' : IDL.Float64,
    'phone' : IDL.Text,
    'applicationDate' : IDL.Int,
    'currentStatus' : Status,
    'deletedAt' : IDL.Opt(IDL.Int),
    'netProfit' : IDL.Float64,
    'documentBlobIds' : IDL.Vec(ExternalBlob),
    'customServiceName' : IDL.Opt(IDL.Text),
  });
  const RenewalRecord = IDL.Record({
    'id' : IDL.Text,
    'documentBlob' : IDL.Opt(ExternalBlob),
    'serviceName' : IDL.Text,
    'govtFees' : IDL.Float64,
    'serviceCharge' : IDL.Float64,
    'createdAt' : IDL.Int,
    'totalCharged' : IDL.Float64,
    'nextExpiryDate' : IDL.Int,
    'advancePaid' : IDL.Float64,
    'balanceDue' : IDL.Float64,
    'customerId' : IDL.Text,
    'renewalDate' : IDL.Int,
  });
  const ExpenseSummary = IDL.Record({
    'today' : IDL.Float64,
    'total' : IDL.Float64,
    'thisMonth' : IDL.Float64,
  });
  const ProfitSummary = IDL.Record({
    'today' : IDL.Float64,
    'thisMonth' : IDL.Float64,
    'totalNetProfit' : IDL.Float64,
  });
  const CustomServiceEntry = IDL.Record({
    'name' : IDL.Text,
    'addedAt' : IDL.Int,
    'category' : IDL.Text,
  });
  const DocumentLibraryItem = IDL.Record({
    'id' : IDL.Text,
    'serviceName' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Opt(IDL.Text),
    'uploadedAt' : IDL.Int,
  });
  const ExpenseRecord = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomService' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'addDocumentLibraryItem' : IDL.Func([DocumentLibraryInput], [IDL.Text], []),
    'addExpense' : IDL.Func([ExpenseInput], [IDL.Text], []),
    'addRenewalRecord' : IDL.Func([RenewalInput], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'createCustomer' : IDL.Func([CustomerInput], [IDL.Text], []),
    'deleteDocumentLibraryItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteExpense' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [CustomerRecord], ['query']),
    'getCustomerRenewalHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RenewalRecord)],
        ['query'],
      ),
    'getExpenseSummary' : IDL.Func([], [ExpenseSummary], ['query']),
    'getProfitSummary' : IDL.Func([], [ProfitSummary], ['query']),
    'getUpcomingRenewals' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CustomerRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomServices' : IDL.Func(
        [],
        [IDL.Vec(CustomServiceEntry)],
        ['query'],
      ),
    'listCustomers' : IDL.Func([], [IDL.Vec(CustomerRecord)], ['query']),
    'listDeletedCustomers' : IDL.Func([], [IDL.Vec(CustomerRecord)], ['query']),
    'listDocumentLibraryItems' : IDL.Func(
        [],
        [IDL.Vec(DocumentLibraryItem)],
        ['query'],
      ),
    'listExpenses' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
    'restoreCustomer' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'softDeleteCustomer' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateCustomer' : IDL.Func([IDL.Text, CustomerInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };