/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomServiceEntry {
  'name' : string,
  'addedAt' : bigint,
  'category' : string,
}
export interface CustomerInput {
  'serviceType' : string,
  'serviceCategory' : string,
  'govtFees' : number,
  'applicationNo' : [] | [string],
  'expiryDate' : [] | [bigint],
  'name' : string,
  'deliveryDate' : [] | [bigint],
  'totalCharged' : number,
  'notes' : [] | [string],
  'advancePaid' : number,
  'phone' : string,
  'applicationDate' : bigint,
  'currentStatus' : Status,
  'documentBlobIds' : Array<ExternalBlob>,
  'customServiceName' : [] | [string],
}
export interface CustomerRecord {
  'serviceType' : string,
  'serviceCategory' : string,
  'isDeleted' : boolean,
  'tokenId' : string,
  'govtFees' : number,
  'applicationNo' : [] | [string],
  'expiryDate' : [] | [bigint],
  'name' : string,
  'createdAt' : bigint,
  'deliveryDate' : [] | [bigint],
  'totalCharged' : number,
  'updatedAt' : bigint,
  'notes' : [] | [string],
  'advancePaid' : number,
  'balanceDue' : number,
  'phone' : string,
  'applicationDate' : bigint,
  'currentStatus' : Status,
  'deletedAt' : [] | [bigint],
  'netProfit' : number,
  'documentBlobIds' : Array<ExternalBlob>,
  'customServiceName' : [] | [string],
}
export interface DocumentLibraryInput {
  'serviceName' : string,
  'blob' : ExternalBlob,
  'description' : [] | [string],
}
export interface DocumentLibraryItem {
  'id' : string,
  'serviceName' : string,
  'blob' : ExternalBlob,
  'description' : [] | [string],
  'uploadedAt' : bigint,
}
export interface ExpenseInput {
  'date' : bigint,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface ExpenseRecord {
  'id' : string,
  'date' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface ExpenseSummary {
  'today' : number,
  'total' : number,
  'thisMonth' : number,
}
export type ExternalBlob = Uint8Array;
export interface ProfitSummary {
  'today' : number,
  'thisMonth' : number,
  'totalNetProfit' : number,
}
export interface RenewalInput {
  'documentBlob' : [] | [ExternalBlob],
  'serviceName' : string,
  'govtFees' : number,
  'serviceCharge' : number,
  'nextExpiryDate' : bigint,
  'advancePaid' : number,
  'customerId' : string,
  'renewalDate' : bigint,
}
export interface RenewalRecord {
  'id' : string,
  'documentBlob' : [] | [ExternalBlob],
  'serviceName' : string,
  'govtFees' : number,
  'serviceCharge' : number,
  'createdAt' : bigint,
  'totalCharged' : number,
  'nextExpiryDate' : bigint,
  'advancePaid' : number,
  'balanceDue' : number,
  'customerId' : string,
  'renewalDate' : bigint,
}
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'in_process' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomService' : ActorMethod<[string, string], boolean>,
  'addDocumentLibraryItem' : ActorMethod<[DocumentLibraryInput], string>,
  'addExpense' : ActorMethod<[ExpenseInput], string>,
  'addRenewalRecord' : ActorMethod<[RenewalInput], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'createCustomer' : ActorMethod<[CustomerInput], string>,
  'deleteDocumentLibraryItem' : ActorMethod<[string], boolean>,
  'deleteExpense' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], CustomerRecord>,
  'getCustomerRenewalHistory' : ActorMethod<[string], Array<RenewalRecord>>,
  'getExpenseSummary' : ActorMethod<[], ExpenseSummary>,
  'getProfitSummary' : ActorMethod<[], ProfitSummary>,
  'getUpcomingRenewals' : ActorMethod<[bigint], Array<CustomerRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCustomServices' : ActorMethod<[], Array<CustomServiceEntry>>,
  'listCustomers' : ActorMethod<[], Array<CustomerRecord>>,
  'listDeletedCustomers' : ActorMethod<[], Array<CustomerRecord>>,
  'listDocumentLibraryItems' : ActorMethod<[], Array<DocumentLibraryItem>>,
  'listExpenses' : ActorMethod<[], Array<ExpenseRecord>>,
  'restoreCustomer' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'softDeleteCustomer' : ActorMethod<[string], boolean>,
  'updateCustomer' : ActorMethod<[string, CustomerInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];