/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface RenewalInput {
    documentBlob?: ExternalBlob;
    serviceName: string;
    govtFees: number;
    serviceCharge: number;
    nextExpiryDate: bigint;
    advancePaid: number;
    customerId: string;
    renewalDate: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ExpenseRecord {
    id: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    category: string;
    amount: number;
}
export interface DocumentLibraryInput {
    serviceName: string;
    blob: ExternalBlob;
    description?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CustomerInput {
    serviceType: string;
    serviceCategory: string;
    govtFees: number;
    applicationNo?: string;
    expiryDate?: bigint;
    name: string;
    deliveryDate?: bigint;
    totalCharged: number;
    notes?: string;
    advancePaid: number;
    phone: string;
    applicationDate: bigint;
    currentStatus: Status;
    documentBlobIds: Array<ExternalBlob>;
    customServiceName?: string;
}
export interface CustomerRecord {
    serviceType: string;
    serviceCategory: string;
    isDeleted: boolean;
    tokenId: string;
    govtFees: number;
    applicationNo?: string;
    expiryDate?: bigint;
    name: string;
    createdAt: bigint;
    deliveryDate?: bigint;
    totalCharged: number;
    updatedAt: bigint;
    notes?: string;
    advancePaid: number;
    balanceDue: number;
    phone: string;
    applicationDate: bigint;
    currentStatus: Status;
    deletedAt?: bigint;
    netProfit: number;
    documentBlobIds: Array<ExternalBlob>;
    customServiceName?: string;
}
export interface CustomServiceEntry {
    name: string;
    addedAt: bigint;
    category: string;
}
export interface RenewalRecord {
    id: string;
    documentBlob?: ExternalBlob;
    serviceName: string;
    govtFees: number;
    serviceCharge: number;
    createdAt: bigint;
    totalCharged: number;
    nextExpiryDate: bigint;
    advancePaid: number;
    balanceDue: number;
    customerId: string;
    renewalDate: bigint;
}
export interface DocumentLibraryItem {
    id: string;
    serviceName: string;
    blob: ExternalBlob;
    description?: string;
    uploadedAt: bigint;
}
export interface ExpenseInput {
    date: bigint;
    description: string;
    category: string;
    amount: number;
}
export interface ProfitSummary {
    today: number;
    thisMonth: number;
    totalNetProfit: number;
}
export interface UserProfile {
    name: string;
}
export interface ExpenseSummary {
    today: number;
    total: number;
    thisMonth: number;
}
export enum Status {
    pending = "pending",
    completed = "completed",
    in_process = "in_process"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomService(name: string, category: string): Promise<boolean>;
    addDocumentLibraryItem(input: DocumentLibraryInput): Promise<string>;
    addExpense(input: ExpenseInput): Promise<string>;
    addRenewalRecord(input: RenewalInput): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimFirstAdmin(): Promise<boolean>;
    createCustomer(input: CustomerInput): Promise<string>;
    deleteDocumentLibraryItem(id: string): Promise<boolean>;
    deleteExpense(id: string): Promise<boolean>;
    deleteRenewalRecord(id: string): Promise<boolean>;
    getAllRenewalHistory(): Promise<Array<RenewalRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(tokenId: string): Promise<CustomerRecord>;
    getCustomerRenewalHistory(customerId: string): Promise<Array<RenewalRecord>>;
    getExpenseSummary(): Promise<ExpenseSummary>;
    getProfitSummary(): Promise<ProfitSummary>;
    getUpcomingRenewals(daysAhead: bigint): Promise<Array<CustomerRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listCustomServices(): Promise<Array<CustomServiceEntry>>;
    listCustomers(): Promise<Array<CustomerRecord>>;
    listDeletedCustomers(): Promise<Array<CustomerRecord>>;
    listDocumentLibraryItems(): Promise<Array<DocumentLibraryItem>>;
    listExpenses(): Promise<Array<ExpenseRecord>>;
    restoreCustomer(tokenId: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    softDeleteCustomer(tokenId: string): Promise<boolean>;
    updateCustomer(tokenId: string, input: CustomerInput): Promise<boolean>;
    updateRenewalRecord(id: string, input: RenewalInput): Promise<boolean>;
}
import type { CustomerInput as _CustomerInput, CustomerRecord as _CustomerRecord, DocumentLibraryInput as _DocumentLibraryInput, DocumentLibraryItem as _DocumentLibraryItem, ExternalBlob as _ExternalBlob, RenewalInput as _RenewalInput, RenewalRecord as _RenewalRecord, Status as _Status, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomService(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomService(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomService(arg0, arg1);
            return result;
        }
    }
    async addDocumentLibraryItem(arg0: DocumentLibraryInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocumentLibraryItem(await to_candid_DocumentLibraryInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocumentLibraryItem(await to_candid_DocumentLibraryInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addExpense(arg0: ExpenseInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0);
            return result;
        }
    }
    async addRenewalRecord(arg0: RenewalInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addRenewalRecord(await to_candid_RenewalInput_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRenewalRecord(await to_candid_RenewalInput_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimFirstAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimFirstAdmin();
            return result;
        }
    }
    async createCustomer(arg0: CustomerInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(await to_candid_CustomerInput_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(await to_candid_CustomerInput_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteDocumentLibraryItem(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocumentLibraryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocumentLibraryItem(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteRenewalRecord(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRenewalRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRenewalRecord(arg0);
            return result;
        }
    }
    async getAllRenewalHistory(): Promise<Array<RenewalRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRenewalHistory();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRenewalHistory();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: string): Promise<CustomerRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_CustomerRecord_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_CustomerRecord_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerRenewalHistory(arg0: string): Promise<Array<RenewalRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerRenewalHistory(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerRenewalHistory(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenseSummary(): Promise<ExpenseSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseSummary();
            return result;
        }
    }
    async getProfitSummary(): Promise<ProfitSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitSummary();
            return result;
        }
    }
    async getUpcomingRenewals(arg0: bigint): Promise<Array<CustomerRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingRenewals(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingRenewals(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCustomServices(): Promise<Array<CustomServiceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomServices();
            return result;
        }
    }
    async listCustomers(): Promise<Array<CustomerRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDeletedCustomers(): Promise<Array<CustomerRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDeletedCustomers();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDeletedCustomers();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDocumentLibraryItems(): Promise<Array<DocumentLibraryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocumentLibraryItems();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocumentLibraryItems();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listExpenses(): Promise<Array<ExpenseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpenses();
            return result;
        }
    }
    async restoreCustomer(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreCustomer(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async softDeleteCustomer(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.softDeleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.softDeleteCustomer(arg0);
            return result;
        }
    }
    async updateCustomer(arg0: string, arg1: CustomerInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, await to_candid_CustomerInput_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, await to_candid_CustomerInput_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRenewalRecord(arg0: string, arg1: RenewalInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRenewalRecord(arg0, await to_candid_RenewalInput_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRenewalRecord(arg0, await to_candid_RenewalInput_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_CustomerRecord_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerRecord): Promise<CustomerRecord> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_DocumentLibraryItem_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentLibraryItem): Promise<DocumentLibraryItem> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_RenewalRecord_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RenewalRecord): Promise<RenewalRecord> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    documentBlob: [] | [_ExternalBlob];
    serviceName: string;
    govtFees: number;
    serviceCharge: number;
    createdAt: bigint;
    totalCharged: number;
    nextExpiryDate: bigint;
    advancePaid: number;
    balanceDue: number;
    customerId: string;
    renewalDate: bigint;
}): Promise<{
    id: string;
    documentBlob?: ExternalBlob;
    serviceName: string;
    govtFees: number;
    serviceCharge: number;
    createdAt: bigint;
    totalCharged: number;
    nextExpiryDate: bigint;
    advancePaid: number;
    balanceDue: number;
    customerId: string;
    renewalDate: bigint;
}> {
    return {
        id: value.id,
        documentBlob: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.documentBlob)),
        serviceName: value.serviceName,
        govtFees: value.govtFees,
        serviceCharge: value.serviceCharge,
        createdAt: value.createdAt,
        totalCharged: value.totalCharged,
        nextExpiryDate: value.nextExpiryDate,
        advancePaid: value.advancePaid,
        balanceDue: value.balanceDue,
        customerId: value.customerId,
        renewalDate: value.renewalDate
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: string;
    serviceCategory: string;
    isDeleted: boolean;
    tokenId: string;
    govtFees: number;
    applicationNo: [] | [string];
    expiryDate: [] | [bigint];
    name: string;
    createdAt: bigint;
    deliveryDate: [] | [bigint];
    totalCharged: number;
    updatedAt: bigint;
    notes: [] | [string];
    advancePaid: number;
    balanceDue: number;
    phone: string;
    applicationDate: bigint;
    currentStatus: _Status;
    deletedAt: [] | [bigint];
    netProfit: number;
    documentBlobIds: Array<_ExternalBlob>;
    customServiceName: [] | [string];
}): Promise<{
    serviceType: string;
    serviceCategory: string;
    isDeleted: boolean;
    tokenId: string;
    govtFees: number;
    applicationNo?: string;
    expiryDate?: bigint;
    name: string;
    createdAt: bigint;
    deliveryDate?: bigint;
    totalCharged: number;
    updatedAt: bigint;
    notes?: string;
    advancePaid: number;
    balanceDue: number;
    phone: string;
    applicationDate: bigint;
    currentStatus: Status;
    deletedAt?: bigint;
    netProfit: number;
    documentBlobIds: Array<ExternalBlob>;
    customServiceName?: string;
}> {
    return {
        serviceType: value.serviceType,
        serviceCategory: value.serviceCategory,
        isDeleted: value.isDeleted,
        tokenId: value.tokenId,
        govtFees: value.govtFees,
        applicationNo: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.applicationNo)),
        expiryDate: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.expiryDate)),
        name: value.name,
        createdAt: value.createdAt,
        deliveryDate: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.deliveryDate)),
        totalCharged: value.totalCharged,
        updatedAt: value.updatedAt,
        notes: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.notes)),
        advancePaid: value.advancePaid,
        balanceDue: value.balanceDue,
        phone: value.phone,
        applicationDate: value.applicationDate,
        currentStatus: from_candid_Status_n32(_uploadFile, _downloadFile, value.currentStatus),
        deletedAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.deletedAt)),
        netProfit: value.netProfit,
        documentBlobIds: await from_candid_vec_n34(_uploadFile, _downloadFile, value.documentBlobIds),
        customServiceName: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.customServiceName))
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    serviceName: string;
    blob: _ExternalBlob;
    description: [] | [string];
    uploadedAt: bigint;
}): Promise<{
    id: string;
    serviceName: string;
    blob: ExternalBlob;
    description?: string;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        serviceName: value.serviceName,
        blob: await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.blob),
        description: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.description)),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    in_process: null;
}): Status {
    return "pending" in value ? Status.pending : "completed" in value ? Status.completed : "in_process" in value ? Status.in_process : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RenewalRecord>): Promise<Array<RenewalRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_RenewalRecord_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerRecord>): Promise<Array<CustomerRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CustomerRecord_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentLibraryItem>): Promise<Array<DocumentLibraryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DocumentLibraryItem_n37(_uploadFile, _downloadFile, x)));
}
async function to_candid_CustomerInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerInput): Promise<_CustomerInput> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_DocumentLibraryInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentLibraryInput): Promise<_DocumentLibraryInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_RenewalInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RenewalInput): Promise<_RenewalInput> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documentBlob?: ExternalBlob;
    serviceName: string;
    govtFees: number;
    serviceCharge: number;
    nextExpiryDate: bigint;
    advancePaid: number;
    customerId: string;
    renewalDate: bigint;
}): Promise<{
    documentBlob: [] | [_ExternalBlob];
    serviceName: string;
    govtFees: number;
    serviceCharge: number;
    nextExpiryDate: bigint;
    advancePaid: number;
    customerId: string;
    renewalDate: bigint;
}> {
    return {
        documentBlob: value.documentBlob ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.documentBlob)) : candid_none(),
        serviceName: value.serviceName,
        govtFees: value.govtFees,
        serviceCharge: value.serviceCharge,
        nextExpiryDate: value.nextExpiryDate,
        advancePaid: value.advancePaid,
        customerId: value.customerId,
        renewalDate: value.renewalDate
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: string;
    serviceCategory: string;
    govtFees: number;
    applicationNo?: string;
    expiryDate?: bigint;
    name: string;
    deliveryDate?: bigint;
    totalCharged: number;
    notes?: string;
    advancePaid: number;
    phone: string;
    applicationDate: bigint;
    currentStatus: Status;
    documentBlobIds: Array<ExternalBlob>;
    customServiceName?: string;
}): Promise<{
    serviceType: string;
    serviceCategory: string;
    govtFees: number;
    applicationNo: [] | [string];
    expiryDate: [] | [bigint];
    name: string;
    deliveryDate: [] | [bigint];
    totalCharged: number;
    notes: [] | [string];
    advancePaid: number;
    phone: string;
    applicationDate: bigint;
    currentStatus: _Status;
    documentBlobIds: Array<_ExternalBlob>;
    customServiceName: [] | [string];
}> {
    return {
        serviceType: value.serviceType,
        serviceCategory: value.serviceCategory,
        govtFees: value.govtFees,
        applicationNo: value.applicationNo ? candid_some(value.applicationNo) : candid_none(),
        expiryDate: value.expiryDate ? candid_some(value.expiryDate) : candid_none(),
        name: value.name,
        deliveryDate: value.deliveryDate ? candid_some(value.deliveryDate) : candid_none(),
        totalCharged: value.totalCharged,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        advancePaid: value.advancePaid,
        phone: value.phone,
        applicationDate: value.applicationDate,
        currentStatus: to_candid_Status_n17(_uploadFile, _downloadFile, value.currentStatus),
        documentBlobIds: await to_candid_vec_n19(_uploadFile, _downloadFile, value.documentBlobIds),
        customServiceName: value.customServiceName ? candid_some(value.customServiceName) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceName: string;
    blob: ExternalBlob;
    description?: string;
}): Promise<{
    serviceName: string;
    blob: _ExternalBlob;
    description: [] | [string];
}> {
    return {
        serviceName: value.serviceName,
        blob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.blob),
        description: value.description ? candid_some(value.description) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    pending: null;
} | {
    completed: null;
} | {
    in_process: null;
} {
    return value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.in_process ? {
        in_process: null
    } : value;
}
async function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
